echo "////////////////////////"
echo ""
echo "Installation en cours..."
echo ""
./install.sh
echo ""
echo "Fin de l'installation !"
echo ""
echo "////////////////////////"
echo ""
echo "Création du docker-compose en cours..."
echo ""
docker-compose up -d
echo ""
echo "Fin de l'installation du docker-compose!"
echo ""
echo "////////////////////////"
echo ""
echo "Mise en place de la sauvegarde des données automatique hebdomadaire en cours..."
echo ""
./crontab_setup.sh
echo ""
echo "Fin de l'installation de la sauvegarde automatique !"
echo ""
echo "////////////////////////"
